name: Quasar Develop

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-spa:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 16
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install packages
        run: |
          npm install -g @quasar/cli
          npm install

      - name: Build the app for development
        run: |
          quasar build -m spa

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: Nebula_SPA
          path: dist/spa
