name: Quasar Release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install packages
        run: |
          npm install -g @quasar/cli
          npm install

      - name: Build the app for production
        run: |
          quasar build

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: Nebula_Release
          path: dist/spa
